#==============================================
# Macros for installing libraries
#==============================================

MACRO (CDAQ_INSTALL_LIB NAME)
IF (NOT WIN32)
  INSTALL(TARGETS ${NAME} ${NAME} ${NAME}
    LIBRARY DESTINATION ${CDAQ_LIBRARY_OUTPUT_DIR}
    COMPONENT libraries
    ARCHIVE DESTINATION ${CDAQ_LIBRARY_OUTPUT_DIR}
    COMPONENT libraries
    RUNTIME DESTINATION ${CDAQ_LIBRARY_OUTPUT_DIR}
    COMPONENT libraries
  )
ELSE (NOT WIN32)
  INSTALL(TARGETS ${NAME} ${NAME} ${NAME}
    LIBRARY DESTINATION ${CDAQ_LIBRARY_OUTPUT_DIR}
    COMPONENT libraries
    ARCHIVE DESTINATION ${CDAQ_LIBRARY_OUTPUT_DIR}
    COMPONENT libraries
    RUNTIME DESTINATION ${CDAQ_EXECUTABLE_OUTPUT_DIR}
    COMPONENT applications
  )
ENDIF (NOT WIN32)
ENDMACRO (CDAQ_INSTALL_LIB)

SET(CDAQ_EXECUTABLE_OUTPUT_DIR bin)
SET(CDAQ_LIBRARY_OUTPUT_DIR    lib)

IF(NOT WIN32)
  SET(CDAQ_HEADERS_OUTPUT_DIR  include/cdaq)
  SET(CDAQ_SHARE_OUTPUT_DIR    share/cdaq)
ELSE(NOT WIN32)
  SET(CDAQ_HEADERS_OUTPUT_DIR  include)
  SET(CDAQ_SHARE_OUTPUT_DIR    ./)
ENDIF(NOT WIN32)
SET(CDAQ_TESTS_OUTPUT_DIR      ${CDAQ_BINARY_DIR}/tests)

IF(UNIX)
  SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CDAQ_LIBRARY_DIR})
  SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CDAQ_LIBRARY_DIR})
  SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CDAQ_BINARY_DIR})
ENDIF(UNIX)

IF(MSVC)
  SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG   ${CDAQ_LIBRARY_DIR})
  SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE ${CDAQ_LIBRARY_DIR})
  SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG   ${CDAQ_LIBRARY_DIR})
  SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE ${CDAQ_LIBRARY_DIR})
  SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG   ${CDAQ_BINARY_DIR})
  SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE ${CDAQ_BINARY_DIR})
ENDIF(MSVC)
